### ISSUE TITLE
Running with non-global forcing data

### ISSUE THREAD

**Issue by leiapauline** [NCAR/hrldas#185]
Hello,

I want to run hrldas with my forcing data over 85-165E, -15,35N. I want to reduce the space needed for my input data because our study area is only over a city. What I did was to subset the Zfile and LANDSfile over the same domain as my forcing data. But when I run ./create_forcing.exe, I get an error stating that the z variable can't be read. I checked their structures but I couldn't see any difference. Is there a way for me to make this run possible? I am currently using hrldas on a docker desktop for windows. Any guidance will be much appreciated.

Sincerely,
Leia Pauline

**Comment by cenlinhe** [comment]
what forcing dataset are you using? ERA5-land? GLDAS? or something else?

**Comment by leiapauline** [comment]
I am using ERA5-Land. If it can help, my input files can be found [here](https://drive.google.com/drive/folders/121vepTsVtZqIhcOPu1qNwMyqaj3ZXXoF?usp=sharing).

**Comment by tslin2** [comment]
Hi,

You will have to revise the subroutine code for the regional files, and recompile it (create_forcing.F) due to the default code being read Zfile and LANDSfile as the global domain.

https://github.com/NCAR/hrldas/blob/087f1fd78601b37eaeead93da9f30253441f7cc2/hrldas/HRLDAS_forcing/create_forcing.F#L2090

You should change these two parts at least.
https://github.com/NCAR/hrldas/blob/087f1fd78601b37eaeead93da9f30253441f7cc2/hrldas/HRLDAS_forcing/create_forcing.F#L2100
https://github.com/NCAR/hrldas/blob/087f1fd78601b37eaeead93da9f30253441f7cc2/hrldas/HRLDAS_forcing/create_forcing.F#L2135

**Comment by leiapauline** [comment]
Thanks for the guidance. The recompiled version is running.
