### ISSUE TITLE
The model is gaining water (WaterBalanceError is positive)

### ISSUE THREAD

**Issue by aniketgupta2009** [NCAR/hrldas#74]
Hi,

I am getting a strange error in Noah-MP Version 5 which is "The model is gaining water (WaterBalanceError is positive)". Create forcing is working perfectly using the NLDAS2 Grib files and model writes output for the first 519 timesteps (hourly). It shows the above-mentioned error at the 520th timestep. I tried using the single core as well as multi-cores but the problem persist. A screenshot of the error is attached to this issue.

Please let me know how I could resolve the problem.

Thanking You.

DATA: NLDAS2 Grib Model forcing File
Year: 2017
Timesteps: Hourly

![Noah-MP5_ERROR](https://github.com/NCAR/hrldas/assets/50705068/bf2acbaa-84f2-4904-af35-352b36a9b803)

**Comment by cenlinhe** [comment]
Hi, thank you for your question. Could you please ask your question in the Q&A discussion page: https://github.com/NCAR/hrldas/discussions/categories/q-a
We are asking and answering all questions in the discussion page instead of as an issue so that future users can search all the previous questions. Thank you for your cooperation!

**Comment by cenlinhe** [comment]
This question has been moved and discussed under the discussion Q&A forum: https://github.com/NCAR/hrldas/discussions/75
